# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_nonfnchar_operation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtCore.QObject):
    signal1 = QtCore.pyqtSignal(list)

    def __init__(self, Dialog):
        super(Ui_Dialog, self).__init__(Dialog)
        Dialog.setObjectName("Dialog")
        Dialog.resize(435, 377)
        self.dialog = Dialog
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 310, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_info = QtWidgets.QLabel(Dialog)
        self.label_info.setGeometry(QtCore.QRect(30, 10, 281, 41))
        self.label_info.setObjectName("label_info")
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setGeometry(QtCore.QRect(30, 50, 71, 21))
        self.label_name.setObjectName("label_name")
        self.label_value = QtWidgets.QLabel(Dialog)
        self.label_value.setGeometry(QtCore.QRect(30, 100, 71, 21))
        self.label_value.setObjectName("label_value")
        self.lineEdit_value = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_value.setGeometry(QtCore.QRect(30, 120, 361, 20))
        self.lineEdit_value.setObjectName("lineEdit_value")
        self.label_description = QtWidgets.QLabel(Dialog)
        self.label_description.setGeometry(QtCore.QRect(30, 200, 91, 21))
        self.label_description.setObjectName("label_description")
        self.lineEdit_dataType = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_dataType.setGeometry(QtCore.QRect(30, 170, 361, 20))
        self.lineEdit_dataType.setObjectName("lineEdit_dataType")
        self.label_dataType = QtWidgets.QLabel(Dialog)
        self.label_dataType.setGeometry(QtCore.QRect(30, 150, 71, 21))
        self.label_dataType.setObjectName("label_dataType")
        self.textEdit_description = QtWidgets.QTextEdit(Dialog)
        self.textEdit_description.setGeometry(QtCore.QRect(30, 220, 361, 71))
        self.textEdit_description.setObjectName("textEdit_description")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 70, 361, 21))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_name_value = QtWidgets.QLineEdit(Dialog)
        geek_list = ["", "Interactability", "Availability", "Chronology"]
        self.comboBox.addItems(geek_list)
        self.comboBox.setLineEdit(self.lineEdit_name_value)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.accept_send)
        self.buttonBox.rejected.connect(self.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_info.setText(_translate("Dialog", "Tell us a little something about the\n"
"Non-functional characteristics you want to add."))
        self.label_name.setText(_translate("Dialog", "name:"))
        self.label_value.setText(_translate("Dialog", "value:"))
        self.label_description.setText(_translate("Dialog", "description:"))
        self.label_dataType.setText(_translate("Dialog", "dataType:"))

    def accept_send(self):
        send_list = [1]
        send_list.append(self.lineEdit_name_value.text())
        send_list.append(self.lineEdit_value.text())
        send_list.append(self.lineEdit_dataType.text())
        send_list.append(self.textEdit_description.toPlainText())
        self.signal1.emit(send_list)
        self.dialog.close()

    def reject(self):
        send_list = [0]
        self.signal1.emit(send_list)
        self.dialog.close()


