# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_fnchar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtCore.QObject):
    signal1 = QtCore.pyqtSignal(list)

    def __init__(self, Dialog):
        super(Ui_Dialog, self).__init__(Dialog)
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 244)
        self.dialog = Dialog
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 200, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_title_type = QtWidgets.QLabel(Dialog)
        self.label_title_type.setGeometry(QtCore.QRect(30, 50, 71, 21))
        self.label_title_type.setObjectName("label_title_type")
        self.label_info = QtWidgets.QLabel(Dialog)
        self.label_info.setGeometry(QtCore.QRect(80, 20, 271, 31))
        self.label_info.setObjectName("label_info")
        self.label_title_description = QtWidgets.QLabel(Dialog)
        self.label_title_description.setGeometry(QtCore.QRect(30, 100, 91, 21))
        self.label_title_description.setObjectName("label_title_description")
        self.textEdit_description = QtWidgets.QTextEdit(Dialog)
        self.textEdit_description.setGeometry(QtCore.QRect(30, 120, 361, 71))
        self.textEdit_description.setObjectName("textEdit_description")
        self.lineEdit_type = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_type.setGeometry(QtCore.QRect(30, 70, 361, 20))
        self.lineEdit_type.setObjectName("lineEdit_type")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.accept_send)
        self.buttonBox.rejected.connect(self.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add new Functional_Characteristic"))
        self.label_title_type.setText(_translate("Dialog", "f_type:"))
        self.label_info.setText(_translate("Dialog", "  Tell us a little something about the \n"
"Functional_Characteristic you want to add."))
        self.label_title_description.setText(_translate("Dialog", "description:"))

    def accept_send(self):
        send_list = [1]
        send_list.append(self.lineEdit_type.text())
        send_list.append(self.textEdit_description.toPlainText())
        self.signal1.emit(send_list)
        self.dialog.close()

    def reject(self):
        send_list = [0]
        self.signal1.emit(send_list)
        self.dialog.close()
