# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtCore.QObject):
    signal1 = QtCore.pyqtSignal(list)

    def __init__(self, Dialog):
        super(Ui_Dialog, self).__init__()
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 286)
        self.dialog = Dialog
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_info = QtWidgets.QLabel(Dialog)
        self.label_info.setGeometry(QtCore.QRect(50, 10, 271, 41))
        self.label_info.setObjectName("label_info")
        self.textEdit_decription = QtWidgets.QTextEdit(Dialog)
        self.textEdit_decription.setGeometry(QtCore.QRect(30, 150, 361, 71))
        self.textEdit_decription.setObjectName("textEdit_decription")
        self.lineEdit_uid = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_uid.setGeometry(QtCore.QRect(30, 80, 361, 20))
        self.lineEdit_uid.setObjectName("lineEdit_uid")
        self.label_uid = QtWidgets.QLabel(Dialog)
        self.label_uid.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.label_uid.setObjectName("label_uid")
        self.label_description = QtWidgets.QLabel(Dialog)
        self.label_description.setGeometry(QtCore.QRect(30, 120, 91, 21))
        self.label_description.setObjectName("label_description")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(self.accept_send) # type: ignore
        self.buttonBox.rejected.connect(self.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add new Interface"))
        self.label_info.setText(_translate("Dialog", "Tell us a little something about the\n"
"Interface you want to add."))
        self.label_uid.setText(_translate("Dialog", "uid:"))
        self.label_description.setText(_translate("Dialog", "description:"))

    def accept_send(self):
        send_list = [1]
        send_list.append(self.lineEdit_uid.text())
        send_list.append(self.textEdit_decription.toPlainText())
        self.signal1.emit(send_list)
        self.dialog.close()

    def reject(self):
        send_list = [0]
        self.signal1.emit(send_list)
        self.dialog.close()
